env:
  registryName: qmij2devopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      appenvironment:
        type: choice
        options:
          - dev
          - test
          - prod
          
name: MyJobFamily
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.WTH_QMIJ2 }}
        
    - uses: Azure/arm-deploy@v1.0.9
      with:
        subscriptionId : ${{ secrets.WTH_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.WTH_RESOURCEGROUP }}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webAppName=wth-QMIJ2-${{ github.event.inputs.appenvironment }}
        
  container-build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      run: docker login $registryName -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag
