on:
  workflow_dispatch:
    inputs:
      appenvironment:
        type: choice
        options:
          - dev
          - test
          - prod
          
name: MyJobFamily
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.WTH_QMIJ2 }}
        
    - uses: Azure/arm-deploy@v1.0.9
      with:
        subscriptionId : ${{ secrets.WTH_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.WTH_RESOURCEGROUP }}
        template: ./ARM-Templates/container-webapp-template.json
        parameters: webappName=wth-QMIJ2-${{ github.event.inputs.appenvironment }}
